//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class XSDCustomTool_Parameters : object, System.ComponentModel.INotifyPropertyChanged {
    
    private XSDCustomTool_ParametersXSDexeOptions xSDexeOptionsField;
    
    private string[] elementsToGenerateCodeForField;
    
    /// <remarks/>
    public XSDCustomTool_ParametersXSDexeOptions XSDexeOptions {
        get {
            return this.xSDexeOptionsField;
        }
        set {
            this.xSDexeOptionsField = value;
            this.RaisePropertyChanged("XSDexeOptions");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Element", IsNullable=false)]
    public string[] ElementsToGenerateCodeFor {
        get {
            return this.elementsToGenerateCodeForField;
        }
        set {
            this.elementsToGenerateCodeForField = value;
            this.RaisePropertyChanged("ElementsToGenerateCodeFor");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XSDCustomTool_ParametersXSDexeOptions : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string nameSpaceField;
    
    private XSDCustomTool_ParametersXSDexeOptionsLanguage languageField;
    
    private bool languageFieldSpecified;
    
    private bool noLogoField;
    
    private bool noLogoFieldSpecified;
    
    private bool generateClassField;
    
    private XSDCustomTool_ParametersXSDexeOptionsClassOptions classOptionsField;
    
    private XSDCustomTool_ParametersXSDexeOptionsDataSetOptions dataSetOptionsField;
    
    /// <remarks/>
    public string NameSpace {
        get {
            return this.nameSpaceField;
        }
        set {
            this.nameSpaceField = value;
            this.RaisePropertyChanged("NameSpace");
        }
    }
    
    /// <remarks/>
    public XSDCustomTool_ParametersXSDexeOptionsLanguage Language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
            this.RaisePropertyChanged("Language");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LanguageSpecified {
        get {
            return this.languageFieldSpecified;
        }
        set {
            this.languageFieldSpecified = value;
            this.RaisePropertyChanged("LanguageSpecified");
        }
    }
    
    /// <remarks/>
    public bool NoLogo {
        get {
            return this.noLogoField;
        }
        set {
            this.noLogoField = value;
            this.RaisePropertyChanged("NoLogo");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NoLogoSpecified {
        get {
            return this.noLogoFieldSpecified;
        }
        set {
            this.noLogoFieldSpecified = value;
            this.RaisePropertyChanged("NoLogoSpecified");
        }
    }
    
    /// <remarks/>
    public bool GenerateClass {
        get {
            return this.generateClassField;
        }
        set {
            this.generateClassField = value;
            this.RaisePropertyChanged("GenerateClass");
        }
    }
    
    /// <remarks/>
    public XSDCustomTool_ParametersXSDexeOptionsClassOptions ClassOptions {
        get {
            return this.classOptionsField;
        }
        set {
            this.classOptionsField = value;
            this.RaisePropertyChanged("ClassOptions");
        }
    }
    
    /// <remarks/>
    public XSDCustomTool_ParametersXSDexeOptionsDataSetOptions DataSetOptions {
        get {
            return this.dataSetOptionsField;
        }
        set {
            this.dataSetOptionsField = value;
            this.RaisePropertyChanged("DataSetOptions");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum XSDCustomTool_ParametersXSDexeOptionsLanguage {
    
    /// <remarks/>
    CS,
    
    /// <remarks/>
    VB,
    
    /// <remarks/>
    JS,
    
    /// <remarks/>
    VJS,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XSDCustomTool_ParametersXSDexeOptionsClassOptions : object, System.ComponentModel.INotifyPropertyChanged {
    
    private bool propertiesInsteadOfFieldsField;
    
    private bool propertiesInsteadOfFieldsFieldSpecified;
    
    private bool orderField;
    
    private bool orderFieldSpecified;
    
    private bool enableDataBindingField;
    
    private bool enableDataBindingFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public bool PropertiesInsteadOfFields {
        get {
            return this.propertiesInsteadOfFieldsField;
        }
        set {
            this.propertiesInsteadOfFieldsField = value;
            this.RaisePropertyChanged("PropertiesInsteadOfFields");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PropertiesInsteadOfFieldsSpecified {
        get {
            return this.propertiesInsteadOfFieldsFieldSpecified;
        }
        set {
            this.propertiesInsteadOfFieldsFieldSpecified = value;
            this.RaisePropertyChanged("PropertiesInsteadOfFieldsSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public bool Order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
            this.RaisePropertyChanged("Order");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OrderSpecified {
        get {
            return this.orderFieldSpecified;
        }
        set {
            this.orderFieldSpecified = value;
            this.RaisePropertyChanged("OrderSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public bool EnableDataBinding {
        get {
            return this.enableDataBindingField;
        }
        set {
            this.enableDataBindingField = value;
            this.RaisePropertyChanged("EnableDataBinding");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EnableDataBindingSpecified {
        get {
            return this.enableDataBindingFieldSpecified;
        }
        set {
            this.enableDataBindingFieldSpecified = value;
            this.RaisePropertyChanged("EnableDataBindingSpecified");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XSDCustomTool_ParametersXSDexeOptionsDataSetOptions : object, System.ComponentModel.INotifyPropertyChanged {
    
    private bool enableLinqDataSetField;
    
    private bool enableLinqDataSetFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public bool EnableLinqDataSet {
        get {
            return this.enableLinqDataSetField;
        }
        set {
            this.enableLinqDataSetField = value;
            this.RaisePropertyChanged("EnableLinqDataSet");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EnableLinqDataSetSpecified {
        get {
            return this.enableLinqDataSetFieldSpecified;
        }
        set {
            this.enableLinqDataSetFieldSpecified = value;
            this.RaisePropertyChanged("EnableLinqDataSetSpecified");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}
