using System.IO;

namespace XSDCustomToolVSIX.Interfaces
{
    /// <summary> AutoGenerated_Supplement File Generator </summary>
    internal interface ICodeGenerator_SupplementFile : ICodeGenerator
    {

    }
}