using System.CodeDom;
using System.CodeDom.Compiler;
using XSDCustomToolVSIX.BaseClasses;

namespace XSDCustomToolVSIX.Interfaces
{
    /// <summary>
    /// Interface for a ParsedFile object - Represents the file generated by XSD.exe. Contains methods to create classes based off the parsed file.
    /// </summary>
    internal interface IParsedFile
    {

        /// <inheritdoc cref="ParsedFile.xSD_Instance"/>
        XSD_Instance xSD_Instance { get; }

        #region < CodeDom & Settings >

        /// <inheritdoc cref="ParsedFile.TargetNameSpace"/>
        CodeNamespace TargetNameSpace { get; }

        /// <inheritdoc cref="ParsedFile.ParsedCode"/>
        CodeCompileUnit ParsedCode { get; }

        /// <inheritdoc cref="ParsedFile.CodeDomObjectProvider"/>
        ICodeDomObjectProvider CodeDomObjectProvider { get; }

        #endregion

        #region < Discovered Types >

        /// <inheritdoc cref="ParsedFile.TopLevelClass"/>
        DiscoveredClass TopLevelClass { get; }

        /// <inheritdoc cref="ParsedFile.DiscoveredClasses"/>
        DiscoveredClass[] DiscoveredClasses { get; }

        /// <inheritdoc cref="ParsedFile.DiscoveredEnums"/>
        DiscoveredEnum[] DiscoveredEnums { get; }


        /// <inheritdoc cref="ParsedFile.DiscoveredTypes"/>
        CodeTypeDeclarationCollection DiscoveredTypes { get; }

        /// <inheritdoc cref="ParsedFile.FindEnumByName(string)"/>
        DiscoveredEnum FindEnumByName(string name);

        #endregion
    }
}